### ISSUE TITLE
Broken debug build

### ISSUE THREAD

**Issue by Afforix** [therion/therion#246]
Hi, I'm no longer able to build therion in the debug configuration (`make config-debug`), I get this error:
```
g++ -Wall -DTHLINUX -ggdb -DTHDEBUG -DPROJ_VER=6 -I/usr/include -std=c++11 -o ./therion therion-main.cxx  ./thdate.o ./extern/shpopen.o ./extern/dbfopen.o ./thexception.o ./thbuffer.o ./thmbuffer.o ./thlogfile.o ./thtmpdir.o ./thlocale.o ./thparse.o ./thcmdline.o ./thconfig.o ./thinput.o ./thchenc.o ./thdatabase.o ./thdataobject.o ./thdatareader.o ./thsurvey.o ./thendsurvey.o ./thdata.o ./thperson.o ./thtf.o ./thtfangle.o ./thtflength.o ./thtfpwf.o ./thdataleg.o ./thobjectname.o ./thinfnan.o ./thlayout.o ./thlookup.o ./thcomment.o ./thinit.o ./thdb1d.o ./thsvxctrl.o ./thdatastation.o ./thobjectid.o ./thobjectsrc.o ./thgrade.o ./thlibrary.o ./thgeomag.o ./thbezier.o ./thexport.o ./thexporter.o ./thselector.o ./extern/img.o ./thexpmodel.o ./thdb2d00.o ./thscrapis.o ./thcs.o ./thcsdata.o ./thexptable.o ./thdb2d.o ./thscrap.o ./thendscrap.o ./th2ddataobject.o ./thdb2dprj.o ./thdb2dpt.o ./thdb2dlp.o ./thdb2dab.o ./thdb2dji.o ./thdb2dmi.o ./thdb2dcp.o ./thdb2dxm.o ./thdb2dxs.o ./thscraplo.o ./thscraplp.o ./thscrapen.o ./thpoint.o ./thline.o ./tharea.o ./thlegenddata.o ./thmpost.o ./thsymbolsets.o ./thjoin.o ./thmap.o ./thexpmap.o ./thlayoutln.o ./thlayoutclr.o ./thexpsys.o ./thexpuni.o ./thconvert.o ./thpdf.o ./thpdfdbg.o ./thpdfdata.o ./thtexfonts.o ./thsymbolset.o ./thlang.o ./thmapstat.o ./thexpdb.o ./thpic.o ./thsketch.o ./thproj.o ./extern/lxMath.o ./extern/lxFile.o ./thdb3d.o ./thsurface.o ./thimport.o ./thsvg.o ./thepsparse.o ./thtrans.o ./thwarpp.o ./thwarppt.o ./thwarppme.o ./thwarp.o ./thexpshp.o ./thattr.o ./thtex.o ./extern/poly2tri/common/shapes.o ./extern/poly2tri/sweep/advancing_front.o ./extern/poly2tri/sweep/sweep.o ./extern/poly2tri/sweep/cdt.o ./extern/poly2tri/sweep/sweep_context.o ./therion.o ./extern/quickhull/QuickHull.o  -lproj 
therion-main.cxx: In function ‘int main(int, char**)’:
therion-main.cxx:218:21: error: ‘thlog’ was not declared in this scope
  218 |     thdb.self_print(thlog.get_fileh());
      |                     ^~~~~
```
I think it got broken in the commit b7bf1e5b061684b98557da29ddc6fbf92a4213eb, I can compile previous commits without problems.
